server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:26258/chandra_db
    username: chandra
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create-drop

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher